//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ajuste
    {
        public int id_ajuste { get; set; }
        public string observacion { get; set; }
        public Nullable<System.DateTime> fecha_ajuste { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string login_grabacion { get; set; }
        public Nullable<System.DateTime> fecha_grabacion { get; set; }
        public Nullable<int> id_articulo { get; set; }
        public Nullable<int> id_tipo_ajuste { get; set; }
        public Nullable<int> id_herramienta { get; set; }
    
        public virtual articulo articulo { get; set; }
        public virtual herramienta herramienta { get; set; }
        public virtual motivo_ajuste motivo_ajuste { get; set; }
    }
}
