//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public decimal id_cliente { get; set; }
        public decimal id_departamento { get; set; }
        public decimal id_ciudad { get; set; }
        public decimal id_pais { get; set; }
        public string nombre_razon_social_cliente { get; set; }
        public string direccion_cliente { get; set; }
        public Nullable<decimal> telefono_cliente { get; set; }
        public string email_cliente { get; set; }
        public string ci_ruc_cliente { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento_cliente { get; set; }
        public string sexo_cliente { get; set; }
    
        public virtual ciudad ciudad { get; set; }
        public virtual departamento departamento { get; set; }
        public virtual pais pais { get; set; }
    }
}
