//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public compra()
        {
            this.compra_detalle = new HashSet<compra_detalle>();
        }
    
        public int id_compra { get; set; }
        public Nullable<decimal> numero_factura_compra { get; set; }
        public Nullable<decimal> total_iva_5 { get; set; }
        public Nullable<decimal> total_iva_10 { get; set; }
        public Nullable<System.DateTime> fecha_compra { get; set; }
        public Nullable<decimal> monto_total_compra { get; set; }
        public Nullable<decimal> total_iva { get; set; }
        public string login_grabacion { get; set; }
        public Nullable<System.DateTime> fecha_grabacion { get; set; }
        public Nullable<int> id_proveedor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compra_detalle> compra_detalle { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
