//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura_detalle
    {
        public int id_factura_detalle { get; set; }
        public Nullable<int> id_factura { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> precio_unitario { get; set; }
        public Nullable<decimal> excenta { get; set; }
        public Nullable<decimal> iva_5 { get; set; }
        public Nullable<decimal> iva_10 { get; set; }
        public Nullable<int> id_articulo { get; set; }
    
        public virtual articulo articulo { get; set; }
        public virtual factura factura { get; set; }
    }
}
