//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class herramienta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public herramienta()
        {
            this.compra_detalle = new HashSet<compra_detalle>();
            this.salida_herramienta_detalle = new HashSet<salida_herramienta_detalle>();
            this.ajuste = new HashSet<ajuste>();
        }
    
        public int id_herramienta { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<int> id_tipo_herramienta { get; set; }
        public Nullable<int> id_iva { get; set; }
        public Nullable<int> id_grupo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compra_detalle> compra_detalle { get; set; }
        public virtual tipo_herramienta tipo_herramienta { get; set; }
        public virtual impuesto impuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salida_herramienta_detalle> salida_herramienta_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ajuste> ajuste { get; set; }
        public virtual grupo grupo { get; set; }
    }
}
