//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden_trabajo_cabecera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orden_trabajo_cabecera()
        {
            this.orden_trabajo_detalle = new HashSet<orden_trabajo_detalle>();
            this.factura = new HashSet<factura>();
            this.salida_herramienta_cabecera = new HashSet<salida_herramienta_cabecera>();
        }
    
        public int id_orden_trabajo { get; set; }
        public System.DateTime fecha_orden_trabajo { get; set; }
        public int id_presupuesto_cabecera { get; set; }
        public string descripcion_orden_trabajo { get; set; }
    
        public virtual presupuesto_cabecera presupuesto_cabecera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden_trabajo_detalle> orden_trabajo_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura> factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salida_herramienta_cabecera> salida_herramienta_cabecera { get; set; }
    }
}
