//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden_trabajo_detalle
    {
        public int id_orden_trabajo_detalle { get; set; }
        public int id_orden_trabajo { get; set; }
        public int id_articulo { get; set; }
        public int cantidad { get; set; }
        public string descripcion_trabajo { get; set; }
    
        public virtual articulo articulo { get; set; }
        public virtual orden_trabajo_cabecera orden_trabajo_cabecera { get; set; }
    }
}
