//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_detalle
    {
        public int id_presupuesto_detalle { get; set; }
        public int id_presupuesto_cabecera { get; set; }
        public int id_articulo { get; set; }
        public int cantidad { get; set; }
        public decimal precio_unitario { get; set; }
        public Nullable<int> id_tipo_servicio { get; set; }
        public string descripcion { get; set; }
    
        public virtual articulo articulo { get; set; }
        public virtual presupuesto_cabecera presupuesto_cabecera { get; set; }
        public virtual tipo_servicio tipo_servicio { get; set; }
    }
}
