//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salida_herramienta_cabecera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public salida_herramienta_cabecera()
        {
            this.salida_herramienta_detalle = new HashSet<salida_herramienta_detalle>();
        }
    
        public int id_salida_herramienta_cab { get; set; }
        public int id_orden_trabajo { get; set; }
        public System.DateTime fecha_salida { get; set; }
    
        public virtual orden_trabajo_cabecera orden_trabajo_cabecera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salida_herramienta_detalle> salida_herramienta_detalle { get; set; }
    }
}
